apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-test
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      name: network-test
  template:
    metadata:
      labels:
        name: network-test
    spec:
      containers:
      - name: test
        image: curlimages/curl
        command: ["sh", "-c", "sleep 3600"]
