apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # 根据您的 EKS 存储类调整
  resources:
    requests:
      storage: 100Gi