apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgresql
type: Opaque
data:
  # 生成命令: echo -n "yourpassword" | base64
  postgres-password: cG9zdGdyZXMxMjM=  # postgres123
  gitlab-password: Z2l0bGFiMTIzNDU=    # gitlab12345
  replicator-password: cmVwbGljYXRvcjEyMw==  # replicator123
  registry-password: cmVnaXN0cnkxMjM=  # registry123